package com.project.moviestore.model;// Generated Dec 14, 2016 8:17:09 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Sampleview generated by hbm2java
 */
@Entity
@Table(name = "sampleview", catalog = "sakila")
public class Sampleview implements java.io.Serializable {

	private SampleviewId id;

	public Sampleview() {
	}

	public Sampleview(SampleviewId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)),
			@AttributeOverride(name = "name", column = @Column(name = "name", nullable = false, length = 20)),
			@AttributeOverride(name = "lastUpdate", column = @Column(name = "last_update", nullable = false, length = 0)) })
	public SampleviewId getId() {
		return this.id;
	}

	public void setId(SampleviewId id) {
		this.id = id;
	}

}
