package com.project.moviestore.model;// Generated Dec 14, 2016 8:17:09 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SampleviewId generated by hbm2java
 */
@Embeddable
public class SampleviewId implements java.io.Serializable {

	private byte languageId;
	private String name;
	private Date lastUpdate;

	public SampleviewId() {
	}

	public SampleviewId(byte languageId, String name, Date lastUpdate) {
		this.languageId = languageId;
		this.name = name;
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "language_id", nullable = false)
	public byte getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(byte languageId) {
		this.languageId = languageId;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "last_update", nullable = false, length = 0)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SampleviewId))
			return false;
		SampleviewId castOther = (SampleviewId) other;

		return (this.getLanguageId() == castOther.getLanguageId())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getLastUpdate() == castOther.getLastUpdate())
						|| (this.getLastUpdate() != null && castOther.getLastUpdate() != null
								&& this.getLastUpdate().equals(castOther.getLastUpdate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLanguageId();
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getLastUpdate() == null ? 0 : this.getLastUpdate().hashCode());
		return result;
	}

}
